# Generated by Django 4.1 on 2024-01-13 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=64, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='CategoryImages')),
            ],
            options={
                'verbose_name': 'category',
            },
        ),
        migrations.CreateModel(
            name='Coordinadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.CharField(max_length=64)),
                ('lng', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'coordinadas',
            },
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fields', to='MediaManagement.category')),
            ],
            options={
                'verbose_name': 'field',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, unique=True)),
                ('image', models.ImageField(upload_to='PlanImages')),
                ('width', models.CharField(max_length=64)),
                ('height', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'plan',
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MediaManagement.category')),
                ('coordinadas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MediaManagement.coordinadas')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MediaManagement.plan')),
            ],
            options={
                'verbose_name': 'media',
            },
        ),
        migrations.CreateModel(
            name='MediaContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='son_containers', to='MediaManagement.media')),
                ('son', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='father_containers', to='MediaManagement.media')),
            ],
            options={
                'verbose_name': 'media_container',
                'unique_together': {('father', 'son')},
            },
        ),
        migrations.CreateModel(
            name='Media_Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_value', models.CharField(max_length=128)),
                ('link_media', models.CharField(default='', max_length=255)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MediaManagement.field')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_fields', to='MediaManagement.media')),
            ],
            options={
                'verbose_name': 'media_field',
                'unique_together': {('media', 'field')},
            },
        ),
    ]
